import fs from 'node:fs/promises';
import path from 'node:path';
import { PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import type { ObjectStorage, StoredObject } from '@/core/ports';
import { env } from '../env';

interface StorageConfig {
  endpoint: string;
  bucket: string;
  accessKeyId: string;
  secretAccessKey: string;
  region: string;
  publicBaseUrl: string | null;
}

function readConfig(): StorageConfig | null {
  const bucket = env.R2_BUCKET;
  const accessKeyId = env.R2_ACCESS_KEY_ID;
  const secretAccessKey = env.R2_SECRET_ACCESS_KEY;
  if (!bucket || !accessKeyId || !secretAccessKey) return null;

  const endpoint =
    env.R2_ENDPOINT ??
    (env.R2_ACCOUNT_ID ? `https://${env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com` : '');
  if (!endpoint) return null;

  return {
    endpoint,
    bucket,
    accessKeyId,
    secretAccessKey,
    region: env.R2_REGION ?? 'auto',
    publicBaseUrl: env.CDN_HOST ? `https://${env.CDN_HOST.replace(/^https?:\/\//, '').replace(/\/$/, '')}` : null,
  };
}

/**
 * S3-compatible object storage (Cloudflare R2, Backblaze B2, MinIO, S3).
 * When nothing is configured the local-disk adapter is used instead — which is
 * what development does, and what production is forbidden from doing.
 */
export function createObjectStorage(): ObjectStorage {
  const config = readConfig();

  if (!config) {
    return createLocalStorage();
  }

  const client = new S3Client({
    endpoint: config.endpoint,
    region: config.region,
    credentials: { accessKeyId: config.accessKeyId, secretAccessKey: config.secretAccessKey },
    forcePathStyle: false,
  });

  return {
    isConfigured: () => true,
    async put(key, body, contentType): Promise<StoredObject> {
      await client.send(
        new PutObjectCommand({
          Bucket: config.bucket,
          Key: key,
          Body: body,
          ContentType: contentType,
        }),
      );

      const url = config.publicBaseUrl
        ? `${config.publicBaseUrl}/${key}`
        : `${config.endpoint.replace(/\/$/, '')}/${config.bucket}/${key}`;

      return { url, key, size: body.length };
    },
  };
}

const LOCAL_ROOT = path.join(process.cwd(), 'public', 'uploads');

/**
 * Normalise an upload key, or return null if it is not safe to use at all.
 *
 * Keys are generated by us rather than supplied by the caller, so this is
 * defence in depth — but a traversal attempt is either a bug or an attack, and
 * the right response is to refuse it, not to quietly rewrite it into some
 * other path (which can silently collide with a legitimate upload).
 */
export function sanitizeUploadKey(key: string): string | null {
  if (typeof key !== 'string' || key.length === 0) return null;
  // Reject absolute keys, Windows drive letters and any NUL byte, all of which
  // can confuse the filesystem layer downstream.
  if (key.includes('\0') || path.isAbsolute(key) || /^[A-Za-z]:[\\/]/.test(key)) return null;

  const safeKey = path.posix.normalize(key);
  if (safeKey === '.' || safeKey === '..' || path.isAbsolute(safeKey)) return null;
  // Refuse any ".." segment, whichever separator style it arrives in.
  if (safeKey.split(/[/\\]/).includes('..')) return null;

  return safeKey;
}

/**
 * Resolve an upload key to an absolute path inside `root`, or null if the key
 * would land anywhere else.
 *
 * The containment comparison is made against the root with a trailing
 * separator: a bare `startsWith(root)` check is a classic near-miss, because
 * "/app/public/uploads-secret/evil.txt" starts with "/app/public/uploads"
 * without being inside it at all.
 */
export function resolveUploadPath(key: string, root: string = LOCAL_ROOT): string | null {
  const safeKey = sanitizeUploadKey(key);
  if (safeKey === null) return null;

  const target = path.resolve(root, safeKey);
  const rootPrefix = root.endsWith(path.sep) ? root : root + path.sep;
  if (target !== root && !target.startsWith(rootPrefix)) return null;

  return target;
}

export function createLocalStorage(): ObjectStorage {
  return {
    isConfigured: () => false,
    async put(key, body): Promise<StoredObject> {
      const safeKey = sanitizeUploadKey(key);
      const target = safeKey === null ? null : resolveUploadPath(safeKey);
      if (safeKey === null || target === null) {
        throw new Error(`Refusing to write an unsafe upload key: ${key}`);
      }

      await fs.mkdir(path.dirname(target), { recursive: true });
      await fs.writeFile(target, body);

      return { url: `/uploads/${safeKey}`, key: safeKey, size: body.length };
    },
  };
}
